"""empty message

Revision ID: 74a8e8d91ce6
Revises: 5bac1409a850
Create Date: 2018-10-17 16:37:06.884017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a8e8d91ce6'
down_revision = '5bac1409a850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('owner_nickname', sa.String(length=30), nullable=True))
    op.add_column('tweets', sa.Column('owner_username', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'owner_username')
    op.drop_column('tweets', 'owner_nickname')
    # ### end Alembic commands ###
