"""empty message

Revision ID: 896c19f1cb91
Revises: 
Create Date: 2018-10-14 17:50:59.901635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896c19f1cb91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
